### ISSUE TITLE
How to set time in ode_func?

### ISSUE THREAD

**Issue by Zbm1996** [markmbaum/libode#1]
Hi, I couldn't find the input parameter for time in ode_func.
![image](https://user-images.githubusercontent.com/25106682/230288858-7bb3ef4e-eefe-4b44-bd6f-86c49719cddf.png)
Do we have any other method to set time in ode_func?
For example, if we want to solve such kind of ode problem, we need to set current time.
![image](https://user-images.githubusercontent.com/25106682/230289259-e6004795-ed74-4018-a25c-3eeca232f47a.png)

**Comment by markmbaum** [comment]
The integrators assume that the system of ODEs to be solved is in ["autonomous form"](https://en.wikipedia.org/wiki/Autonomous_system_(mathematics)), so time is not an argument to the `ode_fun` definition.

In practice, if you want the independent variable to be accessible from inside the system of equations, you can include it as an additional equation in your system of odes
```
dt/dt = 1
```
and define the system to use the value of `t` appropriately.
